apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
  namespace: so1-fase2
  labels:
    app: nodejs-api
    service: nodejs-api
spec:
  type: ClusterIP  # Solo accesible desde dentro del cluster
  ports:
  - port: 80          # Puerto que expone el servicio
    targetPort: 3000  # Puerto del contenedor (Node.js)
    protocol: TCP
    name: http
  selector:
    app: nodejs-api   # Debe coincidir con los labels del deployment
  
  # Configuración adicional para balanceador de carga
  sessionAffinity: None