apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  namespace: so1-fase2
  labels:
    app: python-api
    service: python-api
spec:
  type: ClusterIP  # Solo accesible desde dentro del cluster
  ports:
  - port: 80          # Puerto que expone el servicio
    targetPort: 5000  # Puerto del contenedor (Flask)
    protocol: TCP
    name: http
  selector:
    app: python-api   # Debe coincidir con los labels del deployment
  
  # Configuración adicional para balanceador de carga
  sessionAffinity: None