apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: so1-fase2
  labels:
    app: python-api
    tier: backend
    language: python
spec:
  replicas: 2  # 2 réplicas para alta disponibilidad
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
        tier: backend
        language: python
    spec:
      containers:
      - name: python-api
        image: gio210/api1-python
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  # Puerto donde Flask escucha
          name: http
          protocol: TCP
        
        # Variables de entorno desde ConfigMaps
        env:
        - name: PORT
          value: "5000"
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: DB_NAME
        
        # Variables sensibles desde Secrets
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_PASSWORD
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Recursos
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      
      # Estrategia de restart
      restartPolicy: Always