# 1. Usa una imagen oficial de Node.js
#    En este caso, usas Node.js 22 que es la versión con la que se desarrollo.
FROM node:22-alpine

# 2. Define el directorio de trabajo dentro del contenedor
#    Todo el código se copiará aquí
WORKDIR /app

# 3. Copia los archivos de dependencias primero para aprovechar la cache de Docker
#    Esto hace que no se reinstalen las dependencias si no han cambiado.
COPY package*.json ./

# 4. Instala las dependencias definidas en package.json
#    Usa `npm ci` si tienes `package-lock.json` para instalaciones más rápidas y seguras
RUN npm install

# 5. Copia el resto del código fuente de la API
COPY . .

# 6. Expón el puerto que usará tu aplicación
#    El valor por defecto en Express es 3000, pero se puede sobreescribir con la variable de entorno PORT
EXPOSE 3000

# 7. Comando por defecto para ejecutar la API
#    Asume que el archivo principal se llama `app.js`
CMD ["node", "app.js"]
